// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MyFinancas.MODEL
{
    public partial class MovimentacaoUsuario
    {
        public string IdeMovimentacao { get; set; }
        public string IdeUsuario { get; set; }
        public int Id { get; set; }

        public virtual Movimentacao IdeMovimentacaoNavigation { get; set; }
        public virtual Usuario IdeUsuarioNavigation { get; set; }
    }
}