// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MyFinancas.MODEL
{
    [Table("movimentacao")]
    public class Movimentacao
    {
        public int Id { get; set; }
        [Key]
        public Guid Ide { get; set; }
        [Required]
        [StringLength(100)]
        public string Descricao { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Valor { get; set; }
        [Required]
        [StringLength(1)]
        public string Tipo { get; set; }
        public Guid IdeUsuario { get; set; }

        public Movimentacao()
        {
            Ide = Guid.Empty;
            Descricao = string.Empty;
            Valor = 0m;
            Tipo = string.Empty;
            IdeUsuario = Guid.Empty;
        }
    }
}