// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace MyFinancas.MODEL
{
    public partial class MyfinancasContext : DbContext
    {
        public MyfinancasContext()
        {
        }

        public MyfinancasContext(DbContextOptions<MyfinancasContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Movimentacao> Movimentacao { get; set; }
        public virtual DbSet<MovimentacaoUsuario> MovimentacaoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-P92MMSS\\SQL2014;Initial Catalog=MyFinancas;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");

            modelBuilder.Entity<Movimentacao>(entity =>
            {
                entity.HasKey(e => e.Ide);

                entity.ToTable("movimentacao");

                entity.Property(e => e.Ide)
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.Descricao)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.Id)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id");

                entity.Property(e => e.Origem)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.Tipo)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);
            });

            modelBuilder.Entity<MovimentacaoUsuario>(entity =>
            {
                entity.ToTable("movimentacao_usuario");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.IdeMovimentacao)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("Ide_Movimentacao");

                entity.Property(e => e.IdeUsuario)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("Ide_Usuario");

                entity.HasOne(d => d.IdeMovimentacaoNavigation)
                    .WithMany(p => p.MovimentacaoUsuario)
                    .HasForeignKey(d => d.IdeMovimentacao)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_movimentacao_usuario_movimentacao");

                entity.HasOne(d => d.IdeUsuarioNavigation)
                    .WithMany(p => p.MovimentacaoUsuario)
                    .HasForeignKey(d => d.IdeUsuario)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_movimentacao_usuario_usuario");
            });

            modelBuilder.Entity<Usuario>(entity =>
            {
                entity.HasKey(e => e.Ide);

                entity.ToTable("usuario");

                entity.Property(e => e.Ide)
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.Id)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id");

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}