// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MyFinancas.MODEL
{
    public partial class Usuario
    {
        public Usuario()
        {
            MovimentacaoUsuario = new HashSet<MovimentacaoUsuario>();
        }

        public int Id { get; set; }
        public string Ide { get; set; }
        public string Nome { get; set; }
        public double Saldo { get; set; }

        public virtual ICollection<MovimentacaoUsuario> MovimentacaoUsuario { get; set; }
    }
}