// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MyFinancas.MODEL
{
    [Table("usuario")]
    public partial class Usuario
    {
        public int Id { get; set; }
        [Key]
        public Guid Ide { get; set; }
        [Required]
        [StringLength(100)]
        public string Nome { get; set; }
        [Required]
        [StringLength(100)]
        public string Senha { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Saldo { get; set; }
    }
}